# This is a basic workflow to help you get started with Actions

name: GitHub Page Deployment

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Configure git
        run: |
          git config --global user.name ${{ github.actor }};
          git config --global user.email '<>';
          git remote set-url origin https://pebabion:${{ secrets.GITHUB_TOKEN }}@github.com/pebabion/pebabion.github.io.git

      - name: Install, build and deploy
        run: |
          npm install;
          npm run deploy
